import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, readCanvasViewport } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Minimap Navigation', () => {
  test('clicking a minimap node focuses the corresponding window with target zoom', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'terminal-minimap-focus-a',
            title: 'terminal-minimap-focus-a',
            position: { x: 120, y: 120 },
            width: 460,
            height: 300,
            kind: 'terminal',
          },
          {
            id: 'task-minimap-focus-b',
            title: 'task-minimap-focus-b',
            position: { x: 1420, y: 960 },
            width: 460,
            height: 280,
            kind: 'task',
            task: {
              requirement: 'Focus from minimap',
              status: 'doing',
              priority: 'medium',
              tags: ['minimap'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
        ],
        {
          settings: {
            focusNodeTargetZoom: 1.35,
          },
        },
      )

      const minimap = window.locator('.workspace-canvas__minimap')
      await expect(minimap).toBeVisible()
      const viewportMask = window.locator('.workspace-canvas__minimap-viewport-mask')
      await expect(viewportMask).toBeVisible()

      const taskNode = window.locator('.task-node').filter({ hasText: 'task-minimap-focus-b' })
      await expect(taskNode).toBeVisible()

      const readCenterDelta = async (): Promise<{ dx: number; dy: number }> => {
        const canvasBox = await window.locator('.workspace-canvas .react-flow').boundingBox()
        const taskBox = await taskNode.boundingBox()

        if (!canvasBox || !taskBox) {
          return {
            dx: Number.POSITIVE_INFINITY,
            dy: Number.POSITIVE_INFINITY,
          }
        }

        return {
          dx: Math.abs(canvasBox.x + canvasBox.width / 2 - (taskBox.x + taskBox.width / 2)),
          dy: Math.abs(canvasBox.y + canvasBox.height / 2 - (taskBox.y + taskBox.height / 2)),
        }
      }

      const deltaBefore = await readCenterDelta()
      expect(deltaBefore.dx).toBeGreaterThan(160)

      const minimapBox = await minimap.boundingBox()
      const flowBox = await window.locator('.workspace-canvas .react-flow').boundingBox()
      if (!minimapBox || !flowBox) {
        throw new Error('minimap or flow bounding box unavailable')
      }

      const viewportMaskStyle = await viewportMask.evaluate(element => {
        const style = window.getComputedStyle(element)
        return {
          backgroundColor: style.backgroundColor,
          borderTopColor: style.borderTopColor,
        }
      })
      expect(viewportMaskStyle.backgroundColor).not.toBe('rgba(0, 0, 0, 0)')
      expect(viewportMaskStyle.borderTopColor).not.toBe('rgba(0, 0, 0, 0)')

      const minimapHeader = window.locator('.workspace-canvas__minimap-viewport-window-header')
      await expect(minimapHeader).toHaveCount(0)

      const viewport = await readCanvasViewport(window)
      const targetNodeFrame = {
        x: 1420,
        y: 960,
        width: 460,
        height: 280,
      }
      const sourceNodeFrame = {
        x: 120,
        y: 120,
        width: 460,
        height: 300,
      }
      const viewBounds = {
        x: -viewport.x / viewport.zoom,
        y: -viewport.y / viewport.zoom,
        width: flowBox.width / viewport.zoom,
        height: flowBox.height / viewport.zoom,
      }
      const boundingRect = {
        x: Math.min(viewBounds.x, sourceNodeFrame.x, targetNodeFrame.x),
        y: Math.min(viewBounds.y, sourceNodeFrame.y, targetNodeFrame.y),
        width:
          Math.max(
            viewBounds.x + viewBounds.width,
            sourceNodeFrame.x + sourceNodeFrame.width,
            targetNodeFrame.x + targetNodeFrame.width,
          ) - Math.min(viewBounds.x, sourceNodeFrame.x, targetNodeFrame.x),
        height:
          Math.max(
            viewBounds.y + viewBounds.height,
            sourceNodeFrame.y + sourceNodeFrame.height,
            targetNodeFrame.y + targetNodeFrame.height,
          ) - Math.min(viewBounds.y, sourceNodeFrame.y, targetNodeFrame.y),
      }
      const scaledWidth = boundingRect.width / minimapBox.width
      const scaledHeight = boundingRect.height / minimapBox.height
      const viewScale = Math.max(scaledWidth, scaledHeight, Number.EPSILON)
      const viewWidth = viewScale * minimapBox.width
      const viewHeight = viewScale * minimapBox.height
      const offset = 5 * viewScale
      const minimapViewBox = {
        x: boundingRect.x - (viewWidth - boundingRect.width) / 2 - offset,
        y: boundingRect.y - (viewHeight - boundingRect.height) / 2 - offset,
        width: viewWidth + offset * 2,
        height: viewHeight + offset * 2,
      }
      const targetCenter = {
        x: targetNodeFrame.x + targetNodeFrame.width / 2,
        y: targetNodeFrame.y + targetNodeFrame.height / 2,
      }

      await window.mouse.click(
        minimapBox.x +
          ((targetCenter.x - minimapViewBox.x) / minimapViewBox.width) * minimapBox.width,
        minimapBox.y +
          ((targetCenter.y - minimapViewBox.y) / minimapViewBox.height) * minimapBox.height,
      )

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1.35, 2)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dx
        })
        .toBeLessThan(150)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dy
        })
        .toBeLessThan(150)
    } finally {
      await electronApp.close()
    }
  })
})
