import { expect, test, type Page } from '@playwright/test'
import {
  beginDragMouse,
  clearAndSeedWorkspace,
  launchApp,
  testWorkspacePath,
} from './workspace-canvas.helpers'

async function measureTaskAgentEdgeGap(window: Page): Promise<{
  edgeRight: number
  edgeTop: number
  edgeBottom: number
  gapX: number
  overlapsVertically: boolean
  targetLeft: number
  targetMidY: number
}> {
  return await window.evaluate(() => {
    const edge = document.querySelector(
      '.workspace-task-agent-edge .react-flow__edge-path',
    ) as SVGGraphicsElement | null
    const targetNode = Array.from(document.querySelectorAll('.react-flow__node')).find(node => {
      return node.querySelector('.terminal-node__title')?.textContent?.includes('codex · gpt-5.2-codex')
    }) as HTMLElement | undefined

    if (!edge || !targetNode) {
      throw new Error('task-agent edge or target node unavailable')
    }

    const edgeRect = edge.getBoundingClientRect()
    const targetRect = targetNode.getBoundingClientRect()
    const targetMidY = targetRect.top + targetRect.height / 2

    return {
      edgeRight: edgeRect.right,
      edgeTop: edgeRect.top,
      edgeBottom: edgeRect.bottom,
      gapX: targetRect.left - edgeRect.right,
      overlapsVertically: targetMidY >= edgeRect.top - 8 && targetMidY <= edgeRect.bottom + 8,
      targetLeft: targetRect.left,
      targetMidY,
    }
  })
}

test.describe('Workspace Canvas - Task Agent Edge Drag', () => {
  test('keeps task-agent edge attached while dragging the linked agent node', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-edge-1',
          title: 'Plan drag edge sync',
          position: { x: 120, y: 180 },
          width: 460,
          height: 320,
          kind: 'task',
          status: null,
          task: {
            requirement: 'Verify task edge stays attached while dragging linked agent node.',
            status: 'doing',
            priority: 'medium',
            tags: ['drag'],
            linkedAgentNodeId: 'agent-edge-1',
            lastRunAt: '2026-04-16T00:00:00.000Z',
            autoGeneratedTitle: false,
            createdAt: '2026-04-16T00:00:00.000Z',
            updatedAt: '2026-04-16T00:00:00.000Z',
          },
        },
        {
          id: 'agent-edge-1',
          title: 'codex · gpt-5.2-codex',
          position: { x: 760, y: 180 },
          width: 520,
          height: 320,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-04-16T00:00:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: '[freecli-test-agent] edge sync',
          agent: {
            provider: 'codex',
            prompt: 'Keep edge attached during drag',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'resume',
            resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
            resumeSessionIdVerified: true,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
      ])

      const taskNode = window.locator('.task-node').first()
      const agentNode = window
        .locator('.react-flow__node')
        .filter({
          has: window.locator('.terminal-node__title', {
            hasText: 'codex · gpt-5.2-codex',
          }),
        })
        .first()
      const header = agentNode.locator('.terminal-node__header')

      await expect(taskNode).toBeVisible()
      await expect(agentNode).toBeVisible()
      await expect(window.locator('.workspace-task-agent-edge')).toHaveCount(1)

      await expect
        .poll(async () => {
          return await measureTaskAgentEdgeGap(window)
        })
        .toMatchObject({
          overlapsVertically: true,
        })
      const initialGap = await measureTaskAgentEdgeGap(window)
      expect(initialGap.gapX).toBeLessThan(32)
      expect(initialGap.overlapsVertically).toBe(true)

      const headerBox = await header.boundingBox()
      if (!headerBox) {
        throw new Error('agent header bounding box unavailable')
      }

      const drag = await beginDragMouse(window, {
        start: {
          x: headerBox.x + 140,
          y: headerBox.y + 16,
        },
        initialTarget: {
          x: headerBox.x + 420,
          y: headerBox.y + 140,
        },
        steps: 18,
        settleAfterPressMs: 48,
        settleBeforeReleaseMs: 0,
        settleAfterReleaseMs: 0,
      })

      try {
        const checkpoints = [
          { x: headerBox.x + 220, y: headerBox.y + 60 },
          { x: headerBox.x + 320, y: headerBox.y + 100 },
          { x: headerBox.x + 420, y: headerBox.y + 140 },
        ]

        for (const point of checkpoints) {
          await drag.moveTo(point, { settleAfterMoveMs: 48 })
          const draggingGap = await measureTaskAgentEdgeGap(window)
          expect(draggingGap.gapX).toBeLessThan(32)
          expect(draggingGap.overlapsVertically).toBe(true)
        }
      } finally {
        await drag.release()
      }

      const releasedGap = await measureTaskAgentEdgeGap(window)
      expect(releasedGap.gapX).toBeLessThan(32)
      expect(releasedGap.overlapsVertically).toBe(true)
    } finally {
      await electronApp.close()
    }
  })

  test('keeps task-agent edge attached while dragging after zoom and selected-surface mode', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'task-edge-zoom',
            title: 'Plan drag edge sync',
            position: { x: 120, y: 180 },
            width: 460,
            height: 320,
            kind: 'task',
            status: null,
            task: {
              requirement: 'Verify task edge stays attached while dragging linked agent node.',
              status: 'doing',
              priority: 'medium',
              tags: ['drag'],
              linkedAgentNodeId: 'agent-edge-zoom',
              lastRunAt: '2026-04-16T00:00:00.000Z',
              autoGeneratedTitle: false,
              createdAt: '2026-04-16T00:00:00.000Z',
              updatedAt: '2026-04-16T00:00:00.000Z',
            },
          },
          {
            id: 'agent-edge-zoom',
            title: 'codex · gpt-5.2-codex',
            position: { x: 760, y: 180 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'running',
            startedAt: '2026-04-16T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            scrollback: '[freecli-test-agent] edge sync',
            agent: {
              provider: 'codex',
              prompt: 'Keep edge attached during drag',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
              resumeSessionIdVerified: true,
              executionDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
            },
          },
          {
            id: 'terminal-edge-helper',
            title: 'terminal-edge-helper',
            position: { x: 1360, y: 180 },
            width: 420,
            height: 280,
            kind: 'terminal',
          },
        ],
        {
          settings: {
            canvasInputMode: 'mouse',
          },
        },
      )

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()
      await zoomInButton.click()
      await zoomInButton.click()

      const agentNode = window
        .locator('.react-flow__node')
        .filter({
          has: window.locator('.terminal-node__title', {
            hasText: 'codex · gpt-5.2-codex',
          }),
        })
        .first()
      const helperNode = window
        .locator('.react-flow__node')
        .filter({
          has: window.locator('.terminal-node__title', {
            hasText: 'terminal-edge-helper',
          }),
        })
        .first()

      await expect(agentNode).toBeVisible()
      await expect(helperNode).toBeVisible()

      await agentNode.locator('.terminal-node__header').click({ position: { x: 48, y: 18 } })
      await window.keyboard.down('Shift')
      try {
        await helperNode.locator('.terminal-node__header').click({ position: { x: 48, y: 18 } })
      } finally {
        await window.keyboard.up('Shift')
      }

      await expect(window.locator('.react-flow__node.selected')).toHaveCount(2)
      await expect(window.locator('.workspace-canvas')).toHaveAttribute(
        'data-cove-drag-surface-selection-mode',
        'true',
      )

      const agentBody = agentNode.locator('.terminal-node__terminal')
      const bodyBox = await agentBody.boundingBox()
      if (!bodyBox) {
        throw new Error('agent terminal body bounding box unavailable')
      }

      const drag = await beginDragMouse(window, {
        start: {
          x: bodyBox.x + bodyBox.width * 0.4,
          y: bodyBox.y + bodyBox.height * 0.35,
        },
        initialTarget: {
          x: bodyBox.x + bodyBox.width * 0.4 + 260,
          y: bodyBox.y + bodyBox.height * 0.35 + 180,
        },
        steps: 20,
        settleAfterPressMs: 48,
        settleBeforeReleaseMs: 0,
        settleAfterReleaseMs: 0,
      })

      try {
        const checkpoints = [
          {
            x: bodyBox.x + bodyBox.width * 0.4 + 120,
            y: bodyBox.y + bodyBox.height * 0.35 + 80,
          },
          {
            x: bodyBox.x + bodyBox.width * 0.4 + 200,
            y: bodyBox.y + bodyBox.height * 0.35 + 140,
          },
          {
            x: bodyBox.x + bodyBox.width * 0.4 + 260,
            y: bodyBox.y + bodyBox.height * 0.35 + 180,
          },
        ]

        for (const point of checkpoints) {
          await drag.moveTo(point, { settleAfterMoveMs: 48 })
          const draggingGap = await measureTaskAgentEdgeGap(window)
          expect(draggingGap.gapX).toBeLessThan(40)
          expect(draggingGap.overlapsVertically).toBe(true)
        }
      } finally {
        await drag.release()
      }

      const releasedGap = await measureTaskAgentEdgeGap(window)
      expect(releasedGap.gapX).toBeLessThan(40)
      expect(releasedGap.overlapsVertically).toBe(true)
    } finally {
      await electronApp.close()
    }
  })
})
