import type { Node } from '@xyflow/react'
import type {
  ImageNodeData,
  NoteNodeData,
  PersistedWorkspaceState,
  TaskNodeData,
  TerminalNodeData,
} from '../types'
import {
  deriveAgentNodeBindingId,
  deriveHostedTerminalBindingId,
} from '@contexts/session/domain/sessionBindingId'

function normalizeRuntimeNodeTitle(value: unknown, kind: TerminalNodeData['kind']): string {
  if (typeof value === 'string') {
    return value
  }

  switch (kind) {
    case 'task':
      return '未命名任务'
    case 'note':
      return '未命名笔记'
    case 'agent':
      return '未命名 Agent'
    case 'image':
      return '未命名图片'
    case 'terminal':
    default:
      return 'terminal'
  }
}

function isTaskNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | null,
): value is TaskNodeData {
  return value !== null && typeof value === 'object' && 'requirement' in value
}

function isNoteNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | null,
): value is NoteNodeData {
  return value !== null && typeof value === 'object' && 'text' in value
}

function isImageNodeData(
  value: TaskNodeData | NoteNodeData | ImageNodeData | null,
): value is ImageNodeData {
  return value !== null && typeof value === 'object' && 'assetId' in value && 'mimeType' in value
}

export function toRuntimeNodes(workspace: PersistedWorkspaceState): Node<TerminalNodeData>[] {
  return workspace.nodes.map(node => {
    const defaultTask: TaskNodeData = {
      requirement: '',
      status: 'todo',
      priority: 'medium',
      tags: [],
      linkedAgentNodeId: null,
      linkedAgentBindingId: null,
      agentSessions: [],
      lastRunAt: null,
      autoGeneratedTitle: false,
      createdAt: null,
      updatedAt: null,
    }
    const task: TaskNodeData | null =
      node.kind === 'task'
        ? isTaskNodeData(node.task)
          ? {
              ...node.task,
              linkedAgentBindingId: node.task.linkedAgentBindingId ?? null,
            }
          : defaultTask
        : null
    const note =
      node.kind === 'note' ? (isNoteNodeData(node.task) ? node.task : { text: '' }) : null
    const image: ImageNodeData | null =
      node.kind === 'image' ? (isImageNodeData(node.task) ? node.task : null) : null

    const runtimeNode: Node<TerminalNodeData> = {
      id: node.id,
      type:
        node.kind === 'task'
          ? 'taskNode'
          : node.kind === 'note'
            ? 'noteNode'
            : node.kind === 'image'
              ? 'imageNode'
              : 'terminalNode',
      position: node.position,
      data: {
        sessionId: '',
        profileId: node.profileId,
        credentialProfileId: node.credentialProfileId ?? null,
        activeCredentialProfileId: node.activeCredentialProfileId ?? null,
        runtimeKind: node.runtimeKind,
        labelColorOverride: node.labelColorOverride ?? null,
        title: normalizeRuntimeNodeTitle(node.title, node.kind),
        titlePinnedByUser: node.titlePinnedByUser === true,
        width: node.width,
        height: node.height,
        kind: node.kind,
        status: node.status,
        startedAt: node.startedAt,
        endedAt: node.endedAt,
        exitCode: node.exitCode,
        lastError: node.lastError,
        scrollback: node.scrollback,
        persistenceMode: 'persistent',
        executionDirectory: node.executionDirectory,
        expectedDirectory: node.expectedDirectory,
        agent: node.agent
          ? {
              ...node.agent,
              bindingId: node.agent.bindingId ?? deriveAgentNodeBindingId(node.id),
            }
          : null,
        hostedAgent: node.hostedAgent
          ? {
              ...node.hostedAgent,
              bindingId: node.hostedAgent.bindingId ?? deriveHostedTerminalBindingId(node.id),
            }
          : null,
        task,
        note,
        image,
      },
      draggable: true,
      selectable: node.kind !== 'note',
    }

    return runtimeNode
  })
}
