import { describe, expect, it } from 'vitest'
import type { Node } from '@xyflow/react'
import type { TerminalNodeData } from '../../../src/contexts/workspace/presentation/renderer/types'
import {
  resolveWorkspaceMinimapNodeHeaderColor,
  resolveWorkspaceMinimapNodeAtPosition,
  resolveWorkspaceMinimapNodeClassName,
  resolveWorkspaceMinimapNodeColor,
  resolveWorkspaceMinimapNodeStrokeColor,
  resolveWorkspaceMinimapViewportWindowLayout,
} from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/minimap'

function createNode(
  overrides: Partial<Node<TerminalNodeData>> & {
    data: Partial<TerminalNodeData> & Pick<TerminalNodeData, 'kind' | 'width' | 'height' | 'title'>
  },
): Node<TerminalNodeData> {
  return {
    id: overrides.id ?? 'node-1',
    type: 'default',
    position: overrides.position ?? { x: 0, y: 0 },
    data: {
      sessionId: 'session-1',
      title: overrides.data.title,
      width: overrides.data.width,
      height: overrides.data.height,
      kind: overrides.data.kind,
      status: overrides.data.status ?? null,
      startedAt: null,
      endedAt: null,
      exitCode: null,
      lastError: null,
      scrollback: null,
      agent: null,
      task: null,
      note: null,
      image: null,
      ...overrides.data,
    },
    ...overrides,
  }
}

describe('workspace minimap helpers', () => {
  it('maps task and agent statuses to minimap colors and classes', () => {
    const taskNode = createNode({
      id: 'task-1',
      data: {
        title: 'task',
        kind: 'task',
        width: 420,
        height: 260,
        task: {
          requirement: 'Implement minimap navigation',
          status: 'doing',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: null,
          agentSessions: [],
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: null,
          updatedAt: null,
        },
      },
    })
    const agentNode = createNode({
      id: 'agent-1',
      data: {
        title: 'agent',
        kind: 'agent',
        width: 420,
        height: 260,
        status: 'standby',
      },
    })

    expect(resolveWorkspaceMinimapNodeColor(taskNode)).toBe(
      'var(--cove-canvas-minimap-node-task-doing)',
    )
    expect(resolveWorkspaceMinimapNodeStrokeColor(taskNode)).toBe(
      'var(--cove-canvas-minimap-node-task-doing-stroke)',
    )
    expect(resolveWorkspaceMinimapNodeClassName(taskNode)).toContain(
      'workspace-canvas__minimap-node--task-doing',
    )
    expect(resolveWorkspaceMinimapNodeHeaderColor(taskNode)).toBe(
      'var(--cove-canvas-minimap-node-task-doing-header)',
    )

    expect(resolveWorkspaceMinimapNodeColor(agentNode)).toBe(
      'var(--cove-canvas-minimap-node-agent-standby)',
    )
    expect(resolveWorkspaceMinimapNodeStrokeColor(agentNode)).toBe(
      'var(--cove-canvas-minimap-node-agent-standby-stroke)',
    )
    expect(resolveWorkspaceMinimapNodeClassName(agentNode)).toContain(
      'workspace-canvas__minimap-node--agent-standby',
    )
    expect(resolveWorkspaceMinimapNodeHeaderColor(agentNode)).toBe(
      'var(--cove-canvas-minimap-node-agent-standby-header)',
    )
  })

  it('maps terminal runtime statuses to minimap colors and classes', () => {
    const runningTerminalNode = createNode({
      id: 'terminal-running',
      data: {
        title: 'running terminal',
        kind: 'terminal',
        width: 420,
        height: 260,
        status: 'running',
      },
    })
    const standbyHostedTerminalNode = createNode({
      id: 'terminal-standby',
      data: {
        title: 'standby terminal',
        kind: 'terminal',
        width: 420,
        height: 260,
        status: 'restoring',
        hostedAgent: {
          provider: 'codex',
          state: 'active',
          promptHint: null,
          lastError: null,
          restoreIntent: true,
          model: null,
        },
      },
    })
    const failedTerminalNode = createNode({
      id: 'terminal-failed',
      data: {
        title: 'failed terminal',
        kind: 'terminal',
        width: 420,
        height: 260,
        status: 'failed',
      },
    })

    expect(resolveWorkspaceMinimapNodeColor(runningTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-running)',
    )
    expect(resolveWorkspaceMinimapNodeClassName(runningTerminalNode)).toContain(
      'workspace-canvas__minimap-node--terminal-running',
    )

    expect(resolveWorkspaceMinimapNodeColor(standbyHostedTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-standby)',
    )
    expect(resolveWorkspaceMinimapNodeClassName(standbyHostedTerminalNode)).toContain(
      'workspace-canvas__minimap-node--terminal-standby',
    )

    expect(resolveWorkspaceMinimapNodeColor(failedTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-inactive)',
    )
    expect(resolveWorkspaceMinimapNodeClassName(failedTerminalNode)).toContain(
      'workspace-canvas__minimap-node--terminal-inactive',
    )
    expect(resolveWorkspaceMinimapNodeStrokeColor(runningTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-running-stroke)',
    )
    expect(resolveWorkspaceMinimapNodeHeaderColor(runningTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-running-header)',
    )
    expect(resolveWorkspaceMinimapNodeStrokeColor(standbyHostedTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-standby-stroke)',
    )
    expect(resolveWorkspaceMinimapNodeHeaderColor(standbyHostedTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-standby-header)',
    )
    expect(resolveWorkspaceMinimapNodeStrokeColor(failedTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-inactive-stroke)',
    )
    expect(resolveWorkspaceMinimapNodeHeaderColor(failedTerminalNode)).toBe(
      'var(--cove-canvas-minimap-node-terminal-inactive-header)',
    )
  })

  it('projects the current viewport into minimap percentage bounds', () => {
    const layout = resolveWorkspaceMinimapViewportWindowLayout({
      nodes: [
        createNode({
          position: { x: 100, y: 120 },
          data: {
            title: 'terminal-a',
            kind: 'terminal',
            width: 400,
            height: 300,
          },
        }),
        createNode({
          id: 'node-2',
          position: { x: 900, y: 620 },
          data: {
            title: 'terminal-b',
            kind: 'terminal',
            width: 480,
            height: 320,
          },
        }),
      ],
      viewport: {
        x: -240,
        y: -180,
        zoom: 1.2,
      },
      flowSize: {
        width: 960,
        height: 720,
      },
      minimapSize: {
        width: 200,
        height: 136,
      },
    })

    expect(layout).not.toBeNull()
    expect(layout!.width).toBeGreaterThan(0)
    expect(layout!.height).toBeGreaterThan(0)
    expect(layout!.left).toBeGreaterThanOrEqual(0)
    expect(layout!.top).toBeGreaterThanOrEqual(0)
    expect(layout!.left + layout!.width).toBeLessThanOrEqual(100)
    expect(layout!.top + layout!.height).toBeLessThanOrEqual(100)
  })

  it('returns null for invalid viewport input', () => {
    const layout = resolveWorkspaceMinimapViewportWindowLayout({
      nodes: [],
      viewport: {
        x: 0,
        y: 0,
        zoom: 0,
      },
      flowSize: {
        width: 0,
        height: 720,
      },
      minimapSize: {
        width: 200,
        height: 136,
      },
    })

    expect(layout).toBeNull()
  })

  it('finds the top-most visible minimap node at a flow position', () => {
    const lowerNode = createNode({
      id: 'lower-node',
      position: { x: 100, y: 100 },
      data: {
        title: 'lower',
        kind: 'terminal',
        width: 400,
        height: 240,
      },
    })
    const topNode = createNode({
      id: 'top-node',
      position: { x: 180, y: 160 },
      data: {
        title: 'top',
        kind: 'task',
        width: 320,
        height: 200,
        task: {
          requirement: 'Layered hit target',
          status: 'todo',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: null,
          agentSessions: [],
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: null,
          updatedAt: null,
        },
      },
    })

    expect(resolveWorkspaceMinimapNodeAtPosition([lowerNode, topNode], { x: 220, y: 220 })?.id).toBe(
      'top-node',
    )
    expect(resolveWorkspaceMinimapNodeAtPosition([lowerNode, topNode], { x: 120, y: 120 })?.id).toBe(
      'lower-node',
    )
    expect(resolveWorkspaceMinimapNodeAtPosition([lowerNode, topNode], { x: 20, y: 20 })).toBeNull()
  })
})
